export const GAME_CONSTANTS = {
  // Timing constants (in milliseconds)
  SPEED_BOOST_DURATION: 5000,
  AUTO_COLLECT_DURATION: 3000,
  RAIN_SHOWER_DURATION: 5000,
  RAIN_SHOWER_INTERVAL: 30000,
  DAMAGE_FLASH_DURATION: 30,
  LIGHTNING_FLASH_DURATION: 150,
  LIGHTNING_INTERVAL_MIN: 3000,
  LIGHTNING_INTERVAL_MAX: 8000,
  HAIL_SLOW_DURATION: 4000, // New: Hail slow effect duration

  // Scoring constants
  NORMAL_DROP_POINTS: 10,
  CORRECT_ORDER_BONUS: 50,
  PERFECT_RAINBOW_BONUS: 100,
  RAINBOW_DROP_POINTS: 50,

  // Game mechanics
  MAX_LIVES: 3,
  HEARTS_PER_PERFECT_RAINBOWS: 3,
  CLOUD_BASE_SPEED: 7,
  CLOUD_SPEED_BOOST_MULTIPLIER: 2,
  CLOUD_SLOW_MULTIPLIER: 0.5, // New: Hail slow effect
  MOUSE_RESPONSIVENESS: 0.15,
  MOUSE_RESPONSIVENESS_LOCKED: 0.8, // New: Different responsiveness for locked cursor

  // Drop spawn rates (percentages)
  RAINBOW_DROP_CHANCE: 0.01, // 1% (reduced from 1.5%)
  GOLDEN_DROP_CHANCE: 0.08, // 7% (0.08 - 0.01)
  BLACK_DROP_CHANCE: 0.2, // 12% (0.20 - 0.08, increased from 10%)
  HEART_DROP_CHANCE: 0.01, // 1%
  HAIL_DROP_CHANCE: 0.25, // 5% (0.25 - 0.20)

  // Visual effects
  PARTICLE_COUNT_NORMAL: 20,
  PARTICLE_COUNT_PERFECT: 50,
  PARTICLE_LIFETIME: 80,
  PERFECT_PARTICLE_LIFETIME: 120,

  // Canvas dimensions
  CANVAS_WIDTH: 800,
  CANVAS_HEIGHT: 600,

  // Drop properties
  DROP_BASE_SPEED: 2,
  RAIN_SPEED_MULTIPLIER: 1.5,
  DROP_RADIUS: 8,
  SPECIAL_DROP_RADIUS: 10,
  LARGE_DROP_RADIUS: 12,

  // Cloud properties
  CLOUD_Y_POSITION: 500,
  CLOUD_COLLISION_RADIUS: 35,
  CLOUD_MIN_X: 40,
  CLOUD_MAX_X: 760,

  // Progress bar
  PROGRESS_BAR_WIDTH: 300,
  PROGRESS_BAR_HEIGHT: 20,
  PROGRESS_BAR_X: 250,
  PROGRESS_BAR_Y: 25,

  // Rainbow arc
  RAINBOW_CENTER_X: 400,
  RAINBOW_CENTER_Y: 80,
  RAINBOW_BASE_RADIUS: 140,
  RAINBOW_SEGMENT_WIDTH: 12,

  // Weather effects
  BACKGROUND_CLOUD_COUNT: 8,
  WIND_COUNT: 5,
  BIRD_COUNT: 3,

  // Day/Night cycle
  PERFECT_RAINBOWS_FOR_NIGHT: 5, // New: Perfect rainbows needed to change time
  STAR_COUNT: 30, // New: Number of stars in night sky
};
