export const GAME_CONSTANTS = {
  // Timing constants (in milliseconds)
  SPEED_BOOST_DURATION: 5000,
  AUTO_COLLECT_DURATION: 3000,
  RAIN_SHOWER_DURATION: 8000,
  RAIN_SHOWER_INTERVAL: 30000,
  DAMAGE_FLASH_DURATION: 30,
  LIGHTNING_FLASH_DURATION: 150,
  LIGHTNING_INTERVAL_MIN: 3000,
  LIGHTNING_INTERVAL_MAX: 8000,
  FREEZE_DURATION: 3000,
  REVERSE_DURATION: 5000,
  DOUBLE_POINTS_DURATION: 10000,
  INVINCIBILITY_DURATION: 3000, // New: 3 seconds invincibility after damage
  SHIELD_DURATION: 6000, // New: 6 seconds shield protection

  // Scoring constants
  NORMAL_DROP_POINTS: 10,
  CORRECT_ORDER_BONUS: 50,
  PERFECT_RAINBOW_BONUS: 100,
  RAINBOW_DROP_POINTS: 50,

  // Game mechanics
  MAX_LIVES: 3,
  CLOUD_BASE_SPEED: 7,
  CLOUD_SPEED_BOOST_MULTIPLIER: 2,
  MOUSE_RESPONSIVENESS: 0.15,
  MOUSE_RESPONSIVENESS_LOCKED: 0.8,

  // Drop spawn rates (percentages) - SPECIAL DROPS ONLY - Balanced
  RAINBOW_DROP_CHANCE: 0.004, // 0.4%
  HEART_DROP_CHANCE: 0.004, // 0.4%
  SHIELD_DROP_CHANCE: 0.025, // 2.5% (between heart and lightning)
  WATER_DROP_CHANCE: 0.012, // 1.2%

  LIGHTNING_DROP_CHANCE: 0.05, // 5%
  HAIL_DROP_CHANCE: 0.05, // 5%
  REVERSE_DROP_CHANCE: 0.05, // 5%
  DOUBLE_DROP_CHANCE: 0.035, // 3.5%

  BOMB_DROP_CHANCE: 0.08, // 8%
  ROCKET_DROP_CHANCE: 0.08, // 8%

  // Total special drops: 0.4% + 0.4% + 2.5% + 1.2% + 5% + 5% + 5% + 3.5% + 8% + 8% = 39%, Normal drops: 61%

  // Drop speed multipliers
  BOMB_SPEED_MULTIPLIER: 1.8,
  REVERSE_SPEED_MULTIPLIER: 1.6,
  HAIL_SPEED_MULTIPLIER: 1.5,
  ROCKET_SPEED_MULTIPLIER: 1.2,
  WATER_SPEED_MULTIPLIER: 1.2,

  // Rocket tracking improvements
  ROCKET_X_SPEED_FACTOR: 0.4, // Slower horizontal movement
  ROCKET_Y_SPEED_FACTOR: 0.6, // Slower vertical movement
  ROCKET_TRACKING_STRENGTH: 0.8, // How strongly rocket tracks cloud

  // Drop spawn timing - Moderate increase
  DROP_SPAWN_RATE_BASE: 250,
  DROP_SPAWN_RATE_RAIN: 120,
  DROP_SPAWN_RATE_FOCUS: 200,
  DROP_SPAWN_RATE_FOCUS_RAIN: 90,

  // Multiple drops per spawn - More conservative
  DROPS_PER_SPAWN_NORMAL: 1,
  DROPS_PER_SPAWN_RAIN: 1,
  DROPS_PER_SPAWN_FOCUS: 2,
  DROPS_PER_SPAWN_FOCUS_RAIN: 2,

  // Visual effects
  PARTICLE_COUNT_NORMAL: 10,
  PARTICLE_COUNT_PERFECT: 30,
  PARTICLE_LIFETIME: 50,
  PERFECT_PARTICLE_LIFETIME: 60,
  INVINCIBILITY_BLINK_SPEED: 1, // How fast cloud blinks during invincibility
  SHIELD_PULSE_SPEED: 0.05, // How fast shield pulses

  // Canvas dimensions - Normal mode
  CANVAS_WIDTH: 800,
  CANVAS_HEIGHT: 650,

  // Canvas dimensions - Focus mode (larger)
  FOCUS_CANVAS_WIDTH: 1200,
  FOCUS_CANVAS_HEIGHT: 800,

  // Drop properties
  DROP_BASE_SPEED: 2,
  RAIN_SPEED_MULTIPLIER: 1.5,
  DROP_RADIUS: 8,
  SPECIAL_DROP_RADIUS: 10,
  LARGE_DROP_RADIUS: 12,

  // Cloud properties - Normal mode
  CLOUD_Y_POSITION: 550,
  CLOUD_COLLISION_RADIUS: 35,
  CLOUD_MIN_X: 40,
  CLOUD_MAX_X: 760,

  // Cloud properties - Focus mode
  FOCUS_CLOUD_Y_POSITION: 700,
  FOCUS_CLOUD_MIN_X: 60,
  FOCUS_CLOUD_MAX_X: 1140,

  // Progress bar
  PROGRESS_BAR_WIDTH: 300,
  PROGRESS_BAR_HEIGHT: 20,
  PROGRESS_BAR_X: 250,
  PROGRESS_BAR_Y: 25,

  // Progress bar - Focus mode
  FOCUS_PROGRESS_BAR_WIDTH: 400,
  FOCUS_PROGRESS_BAR_X: 400,

  // Rainbow arc
  RAINBOW_CENTER_X: 400,
  RAINBOW_CENTER_Y: 80,
  RAINBOW_BASE_RADIUS: 140,
  RAINBOW_SEGMENT_WIDTH: 12,

  // Rainbow arc - Focus mode
  FOCUS_RAINBOW_CENTER_X: 600,
  FOCUS_RAINBOW_CENTER_Y: 100,
  FOCUS_RAINBOW_BASE_RADIUS: 180,

  // Weather effects
  BACKGROUND_CLOUD_COUNT: 8,
  WIND_COUNT: 5,
  BIRD_COUNT: 3,

  // Scene cycle
  PERFECT_RAINBOWS_FOR_SCENE_CHANGE: 5,
  STAR_COUNT: 30,

  // 3D Effects
  CLOUD_BOB_AMPLITUDE: 3,
  CLOUD_BOB_FREQUENCY: 0.02,
  DROP_ROTATION_SPEED: 0.05,
  PARTICLE_Z_RANGE: 50,
  SHADOW_OFFSET_MAX: 8,
};
